name: Backend CI

on:
  pull_request:
    paths:
      - 'starter/backend/**'
  push:
    branches:
      - main
    paths:
      - 'starter/backend/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          cd starter/backend
          pip install -r requirements.txt
      - name: Run lint
        run: |
          cd starter/backend
          pylint **/*.py --exit-zero

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          cd starter/backend
          pip install -r requirements.txt
      - name: Run tests
        run: |
          cd starter/backend
          pytest --disable-warnings
