name: Frontend CD

on:
  push:
    branches:
      - main
    paths:
      - 'starter/frontend/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: |
          cd starter/frontend
          npm install
      - name: Build application
        run: |
          cd starter/frontend
          npm run build
      - name: Build Docker image
        run: |
          cd starter/frontend
          docker build -t frontend:${{ github.sha }} .

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Kubernetes
        run: |
          # Replace with your Kubernetes deployment script
          echo "Deployed frontend to Kubernetes with image tag ${{ github.sha }}"
